{{- /* Module call wiring every module input to a matching root variable. */ -}}
# Generated by scafctl -- do not edit by hand.
module "{{ .moduleName }}" {
  source = "{{ .moduleSource }}"
{{ range .module.inputs }}
  {{ .name }} = var.{{ .name }}
{{- end }}
}
