{{- /* Aggregated variables.tf: re-declares every input of the introspected module. */ -}}
# Generated by scafctl -- do not edit by hand.
# Environment: {{ .environment }}
{{ range .module.inputs }}
variable "{{ .name }}" {
{{- if hasKey . "type" }}
  type = {{ .type }}
{{- end }}
{{- if hasKey . "description" }}
  description = {{ printf "%q" .description }}
{{- end }}
}
{{ end -}}
